/**
 * Comprehensive theme system for the GPA Calculator app
 * Includes multiple themes with interactive theme switching
 */

export const Themes = {
  default: {
    name: 'default',
    displayName: 'Classic Blue',
    colors: {
      primary: '#2196F3',
      secondary: '#1976D2',
      accent: '#64B5F6',
      background: '#F5F5F5',
      surface: '#FFFFFF',
      text: '#333333',
      textSecondary: '#666666',
      border: '#E0E0E0',
      success: '#4CAF50',
      warning: '#FF9800',
      error: '#F44336',
      info: '#2196F3',
      card: '#FFFFFF',
      cardBorder: '#E0E0E0',
      input: '#FFFFFF',
      inputBorder: '#DDDDDD',
      button: '#2196F3',
      buttonText: '#FFFFFF',
      tabActive: '#2196F3',
      tabInactive: '#9E9E9E',
    },
  },
  dark: {
    name: 'dark',
    displayName: 'Dark Mode',
    colors: {
      primary: '#BB86FC',
      secondary: '#03DAC6',
      accent: '#3700B3',
      background: '#121212',
      surface: '#1E1E1E',
      text: '#FFFFFF',
      textSecondary: '#B3B3B3',
      border: '#333333',
      success: '#4CAF50',
      warning: '#FF9800',
      error: '#F44336',
      info: '#2196F3',
      card: '#1E1E1E',
      cardBorder: '#333333',
      input: '#2A2A2A',
      inputBorder: '#444444',
      button: '#BB86FC',
      buttonText: '#000000',
      tabActive: '#BB86FC',
      tabInactive: '#666666',
    },
  },
  ocean: {
    name: 'ocean',
    displayName: 'Ocean Blue',
    colors: {
      primary: '#006064',
      secondary: '#00838F',
      accent: '#26C6DA',
      background: '#E0F2F1',
      surface: '#FFFFFF',
      text: '#004D40',
      textSecondary: '#00695C',
      border: '#B2DFDB',
      success: '#2E7D32',
      warning: '#F57C00',
      error: '#D32F2F',
      info: '#0277BD',
      card: '#FFFFFF',
      cardBorder: '#B2DFDB',
      input: '#FFFFFF',
      inputBorder: '#B2DFDB',
      button: '#006064',
      buttonText: '#FFFFFF',
      tabActive: '#006064',
      tabInactive: '#80CBC4',
    },
  },
  sunset: {
    name: 'sunset',
    displayName: 'Sunset Orange',
    colors: {
      primary: '#FF5722',
      secondary: '#FF7043',
      accent: '#FFAB91',
      background: '#FFF3E0',
      surface: '#FFFFFF',
      text: '#BF360C',
      textSecondary: '#E64A19',
      border: '#FFCC02',
      success: '#388E3C',
      warning: '#F57C00',
      error: '#D32F2F',
      info: '#1976D2',
      card: '#FFFFFF',
      cardBorder: '#FFCC02',
      input: '#FFFFFF',
      inputBorder: '#FFCC02',
      button: '#FF5722',
      buttonText: '#FFFFFF',
      tabActive: '#FF5722',
      tabInactive: '#FFAB91',
    },
  },
  forest: {
    name: 'forest',
    displayName: 'Forest Green',
    colors: {
      primary: '#2E7D32',
      secondary: '#388E3C',
      accent: '#66BB6A',
      background: '#E8F5E8',
      surface: '#FFFFFF',
      text: '#1B5E20',
      textSecondary: '#2E7D32',
      border: '#A5D6A7',
      success: '#2E7D32',
      warning: '#F57C00',
      error: '#D32F2F',
      info: '#1976D2',
      card: '#FFFFFF',
      cardBorder: '#A5D6A7',
      input: '#FFFFFF',
      inputBorder: '#A5D6A7',
      button: '#2E7D32',
      buttonText: '#FFFFFF',
      tabActive: '#2E7D32',
      tabInactive: '#81C784',
    },
  },
  purple: {
    name: 'purple',
    displayName: 'Royal Purple',
    colors: {
      primary: '#6A1B9A',
      secondary: '#8E24AA',
      accent: '#BA68C8',
      background: '#F3E5F5',
      surface: '#FFFFFF',
      text: '#4A148C',
      textSecondary: '#6A1B9A',
      border: '#CE93D8',
      success: '#388E3C',
      warning: '#F57C00',
      error: '#D32F2F',
      info: '#1976D2',
      card: '#FFFFFF',
      cardBorder: '#CE93D8',
      input: '#FFFFFF',
      inputBorder: '#CE93D8',
      button: '#6A1B9A',
      buttonText: '#FFFFFF',
      tabActive: '#6A1B9A',
      tabInactive: '#E1BEE7',
    },
  },
  minimal: {
    name: 'minimal',
    displayName: 'Minimal Gray',
    colors: {
      primary: '#424242',
      secondary: '#616161',
      accent: '#9E9E9E',
      background: '#FAFAFA',
      surface: '#FFFFFF',
      text: '#212121',
      textSecondary: '#757575',
      border: '#E0E0E0',
      success: '#4CAF50',
      warning: '#FF9800',
      error: '#F44336',
      info: '#2196F3',
      card: '#FFFFFF',
      cardBorder: '#E0E0E0',
      input: '#FFFFFF',
      inputBorder: '#E0E0E0',
      button: '#424242',
      buttonText: '#FFFFFF',
      tabActive: '#424242',
      tabInactive: '#BDBDBD',
    },
  },
};

// Legacy support for existing code
export const Colors = {
  light: Themes.default.colors,
  dark: Themes.dark.colors,
}; 